-- Table: Veículo
CREATE TABLE veiculo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    modelo character varying(255) NOT NULL,
	ano int NOT NULL,
	valor float8 NOT NULL,
	marcaId bigint NOT NULL,
    CONSTRAINT veiculo_pkey PRIMARY KEY (id),
	CONSTRAINT veiculo_marca_fkey FOREIGN KEY(marcaId) REFERENCES marca(id)
);

-- Table: Autenticação
CREATE TABLE autenticacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(100) NOT NULL,
	senha character varying(50) NOT NULL,
	salt bytea NOT NULL,
    CONSTRAINT autenticacao_pkey PRIMARY KEY (id)
);